version: '2'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_DB: blog
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password123
      ports:
        - "6479:6479"
        # (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-container        
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:        
        - app_data:/docker_app
        - ./log:/var/log/nginx              
        depends_on:
        - app
        
    app:
        container_name: app-container
        build: ./app
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini         
        ports:
        - "8002:8000"
        volumes:
        - app_data:/docker_app
        depends_on:
        - db

volumes:
    app_data:
    pgdata:

